import type { Metadata } from "next";
/*import { Geist, Geist_Mono, Poppins, Atma } from "next/font/google";*
import "./globals.css";



const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-poppins',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const geistAtma = Atma({
  variable: "--font-atma",
  weight: ['400', '600', '700'],
  subsets: ["latin"],
});*/
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es" /*className={poppins.variable}*/>
      <body className="font-sans">
        {children}
      </body>
    </html>
  )
}
